"""tasks_start_migration

Revision ID: e6bc11a400c0
Revises:
Create Date: 2026-05-02 21:16:40.692481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e6bc11a400c0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("minio_name", sa.String(), nullable=False),
        sa.Column(
            "mime_type",
            sa.Enum(
                "TXT",
                "PNG",
                "JPEG",
                "JPG",
                "DOC",
                "DOCX",
                "XLS",
                "XLSX",
                name="mimetype",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("size > 0", name="attachment_size_range"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column(
            "timezone",
            sa.Enum(
                "MIDWAY",
                "TAHITI",
                "GAMBIER",
                "ANCHORAGE",
                "LOS_ANGELES",
                "MEXICO_CITY",
                "JAMAICA",
                "NEW_YORK",
                "SAO_PAULO",
                "SOUTH_GEORGIA",
                "CAPE_VERDE",
                "UTC",
                "LONDON",
                "PARIS",
                "MOSCOW",
                "DUBAI",
                "ALMATY",
                "OMSK",
                "BANGKOK",
                "HONG_KONG",
                "TOKYO",
                "SYDNEY",
                "SAKHALIN",
                "FIJI",
                name="timezone",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "GUEST", "USER", name="userrole"),
            server_default="USER",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "avatars",
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("minio_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "ON_PAUSE", "DONE", "ARCHIVE", name="projectstatus"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tags_user_id_name"),
    )
    op.create_table(
        "tokens",
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasklists",
        sa.Column("seq_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DONE", name="taskliststatus"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "seq_number", name="uq_tasklist_id_seq_number"
        ),
    )
    op.create_table(
        "tasks",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SCHEDULE", "DONE", name="taskstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MID", "LOW", name="taskpriority"),
            server_default="LOW",
            nullable=False,
        ),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reminder_periodic",
            sa.Enum(
                "NONE",
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "WEEKDAYS",
                name="reminderperiodic",
            ),
            nullable=True,
        ),
        sa.Column("tasklist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["tasklist_id"], ["tasklists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reminders",
        sa.Column("send_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "WEBPUSH", name="reminderchannel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "SENT", name="reminderstatus"),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("was_read", sa.Boolean(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtasks",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "DONE", name="subtaskstatus"),
            server_default="IN_PROGRESS",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_attachments",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"], ["attachments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "attachment_id"),
        sa.UniqueConstraint("task_id", "attachment_id", name="uniq_task_attachment"),
    )
    op.create_table(
        "task_tag",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "tag_id"),
        sa.UniqueConstraint("task_id", "tag_id", name="uniq_task_tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_tag")
    op.drop_table("task_attachments")
    op.drop_table("subtasks")
    op.drop_table("reminders")
    op.drop_table("tasks")
    op.drop_table("tasklists")
    op.drop_table("tokens")
    op.drop_table("tags")
    op.drop_table("projects")
    op.drop_table("avatars")
    op.drop_table("users")
    op.drop_table("attachments")
    # ### end Alembic commands ###
