"""empty message

Revision ID: eb4ee72c9542
Revises: e6bc11a400c0
Create Date: 2026-06-02 07:45:13.864324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4ee72c9542'
down_revision: Union[str, Sequence[str], None] = 'e6bc11a400c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'projects', 'name',
        existing_type=sa.VARCHAR(length=127),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    op.alter_column(
        'subtasks', 'name',
        existing_type=sa.VARCHAR(length=127),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    op.alter_column(
        'tags', 'name',
        existing_type=sa.VARCHAR(length=127),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    op.alter_column(
        'tasklists', 'name',
        existing_type=sa.VARCHAR(length=127),
        type_=sa.String(length=150),
        existing_nullable=False
    )
    op.alter_column(
        'tasks', 'name',
        existing_type=sa.VARCHAR(length=127),
        type_=sa.String(length=150),
        existing_nullable=False
    )

    # 1. Добавляем колонку как разрешающую NULL (nullable=True)
    op.add_column(
        'users', 
        sa.Column('is_blocked', sa.Boolean(), nullable=True)
    )

    # 2. Проставляем всем существующим строкам значение False
    op.execute("UPDATE users SET is_blocked = FALSE")

    # 3. Делаем колонку обязательной к заполнению (nullable=False)
    op.alter_column('users', 'is_blocked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.alter_column(
        'tasks', 'name',
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=127),
        existing_nullable=False
    )
    op.alter_column(
        'tasklists', 'name',
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=127),
        existing_nullable=False
    )
    op.alter_column(
        'tags', 'name',
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=127),
        existing_nullable=False
    )
    op.alter_column(
        'subtasks', 'name',
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=127),
        existing_nullable=False
    )
    op.alter_column(
        'projects', 'name',
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=127),
        existing_nullable=False
    )
