server {
  listen 80;


  location /api/tasks/ {
    client_max_body_size 0;
    proxy_pass http://tasks_backend:8000/;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/flow/ {
    proxy_pass http://flow_backend:8000/;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /minio/ {
    rewrite ^/minio/(.*)$ /$1 break;
    proxy_pass http://minio:9000;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /minio-media/ {
    rewrite ^/minio-media/(.*)$ /$1 break;
    proxy_pass http://minio:9000;

    proxy_set_header Host minio:9000; 
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

}
